### ISSUE TITLE
Update 1.5.10 hass-WEM-Portal

### ISSUE THREAD

**Issue by GAZS-EI** [floek/wemportal#6]
As described in this comment..
https://github.com/erikkastelec/hass-WEM-Portal/issues/96#issuecomment-2395441947
..the URL needs to be changed.
From  <f"{wem_url}/app/**d**evice/Read> to <f"{wem_url}/app/**D**evice/Read">
I tried it myself and now I can receive the data like before as my terminal shows.

It seems like there has been Data added above the "== *device name"==" output-line. It looks like the script now returns detailed settings of the requested machine.

**Comment by floek** [comment]
Hi, can you send a merge request? Best

**Comment by GAZS-EI** [comment]
Hi,
it took me a while, (never used github before) but I now forked your repository, made the change and submitted a pull request.
I hope I did it right :)

**Comment by floek** [comment]
looks fine. thanks. It seems I need to review my ci pipeline.

**Comment by floek** [comment]
Fixed with [v0.0.5](https://github.com/floek/wemportal/releases/tag/v0.0.5)
